POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Dmitrii",
  "password": "password"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRG1pdHJpaSIsImlhdCI6MTYyMzIwMjA0MiwiZXhwIjoxNjIzMjAyMDcyfQ.lLgMzZfn9jZF5vdn_dfD_gUILV-1EqhTJA-vt0a0k6M
###

POST http://localhost:3000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRG1pdHJpaSIsInBhc3N3b3JkIjoiJDJiJDEwJFB0M3hqS1Y1SVFVVk53aVZNa3pLR2VIMU1wYkVDVk5iL0hCeXlrR04xZ3cvbTFWcVM0OWo2IiwiaWF0IjoxNjIzMjAxOTc2fQ.aWYf3jV-YxKjWpWD8tkHPCwsJi3uqTMOtNGsA_JuMks"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Dmitrii",
    "password": "password"

}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRG1pdHJpaSIsImlhdCI6MTYyMzE5MjcyNH0.B4o4NGUG0cgJdgSK3-ZP86neBWRgZaVfjooG8caznA4"
}
